// Code generated by mockery v2.43.2. DO NOT EDIT.

package validation

import mock "github.com/stretchr/testify/mock"

// MockEntityValidation is an autogenerated mock type for the IValidation type
type MockEntityValidation struct {
	mock.Mock
}

type MockEntityValidation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEntityValidation) EXPECT() *MockEntityValidation_Expecter {
	return &MockEntityValidation_Expecter{mock: &_m.Mock}
}

// Entity provides a mock function with given fields: collectionName, entityPath
func (_m *MockEntityValidation) Entity(collectionName string, entityPath string) error {
	ret := _m.Called(collectionName, entityPath)

	if len(ret) == 0 {
		panic("no return value specified for Entity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(collectionName, entityPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityValidation_Entity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entity'
type MockEntityValidation_Entity_Call struct {
	*mock.Call
}

// Entity is a helper method to define mock.On call
//   - collectionName string
//   - entityPath string
func (_e *MockEntityValidation_Expecter) Entity(collectionName interface{}, entityPath interface{}) *MockEntityValidation_Entity_Call {
	return &MockEntityValidation_Entity_Call{Call: _e.mock.On("Entity", collectionName, entityPath)}
}

func (_c *MockEntityValidation_Entity_Call) Run(run func(collectionName string, entityPath string)) *MockEntityValidation_Entity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockEntityValidation_Entity_Call) Return(_a0 error) *MockEntityValidation_Entity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityValidation_Entity_Call) RunAndReturn(run func(string, string) error) *MockEntityValidation_Entity_Call {
	_c.Call.Return(run)
	return _c
}

// EntityUri provides a mock function with given fields: entityUrl
func (_m *MockEntityValidation) EntityUri(entityUrl string) bool {
	ret := _m.Called(entityUrl)

	if len(ret) == 0 {
		panic("no return value specified for EntityUri")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(entityUrl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEntityValidation_EntityUri_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EntityUri'
type MockEntityValidation_EntityUri_Call struct {
	*mock.Call
}

// EntityUri is a helper method to define mock.On call
//   - entityUrl string
func (_e *MockEntityValidation_Expecter) EntityUri(entityUrl interface{}) *MockEntityValidation_EntityUri_Call {
	return &MockEntityValidation_EntityUri_Call{Call: _e.mock.On("EntityUri", entityUrl)}
}

func (_c *MockEntityValidation_EntityUri_Call) Run(run func(entityUrl string)) *MockEntityValidation_EntityUri_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEntityValidation_EntityUri_Call) Return(_a0 bool) *MockEntityValidation_EntityUri_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityValidation_EntityUri_Call) RunAndReturn(run func(string) bool) *MockEntityValidation_EntityUri_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEntityValidation creates a new instance of MockEntityValidation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntityValidation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntityValidation {
	mock := &MockEntityValidation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
