// Code generated by mockery v2.42.1. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockJsonSchema is an autogenerated mock type for the Schema type
type MockJsonSchema struct {
	mock.Mock
}

type MockJsonSchema_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJsonSchema) EXPECT() *MockJsonSchema_Expecter {
	return &MockJsonSchema_Expecter{mock: &_m.Mock}
}

// NewMockJsonSchema creates a new instance of MockJsonSchema. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJsonSchema(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJsonSchema {
	mock := &MockJsonSchema{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
