// Code generated by mockery v2.43.2. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockUtilJsonSchema is an autogenerated mock type for the Schema type
type MockUtilJsonSchema struct {
	mock.Mock
}

type MockUtilJsonSchema_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUtilJsonSchema) EXPECT() *MockUtilJsonSchema_Expecter {
	return &MockUtilJsonSchema_Expecter{mock: &_m.Mock}
}

// NewMockUtilJsonSchema creates a new instance of MockUtilJsonSchema. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUtilJsonSchema(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUtilJsonSchema {
	mock := &MockUtilJsonSchema{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
