resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/AmadlaOrg/hery/cache:
    interfaces:
      Cache:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCache"
          inpackage: True
  github.com/AmadlaOrg/hery/cache/database:
    interfaces:
      Database:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCacheDatabase"
          inpackage: True
      SqlDB:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockSqlDb"
      SqlTx:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockSqlTx"
  github.com/AmadlaOrg/hery/cache/parser:
    interfaces:
      Parser:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCacheParser"
          inpackage: True
  github.com/AmadlaOrg/hery/entity:
    interfaces:
      Service:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntity"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/build:
    interfaces:
      Builder:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityBuild"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/cmd/util:
    interfaces:
      Util:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityCmdUtil"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/get:
    interfaces:
      Getter:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityGet"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/schema:
    interfaces:
      Schema:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntitySchema"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/schema/validation:
    interfaces:
      Validator:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntitySchemaValidation"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/validation:
    interfaces:
      Validator:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityValidation"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/version:
    interfaces:
      Version:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityVersion"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/version/validation:
    interfaces:
      Validator:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityVersionValidation"
          inpackage: True
  github.com/AmadlaOrg/hery/storage:
    interfaces:
      Storage:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockStorage"
          inpackage: True
  sync:
    interfaces:
      Locker:
        config:
          dir: cache/database
          mockName: MockSyncLocker
          inpackage: False
          outpkg: database
