// Code generated by mockery v2.53.6. DO NOT EDIT.

package util

import (
	cobra "github.com/spf13/cobra"
	mock "github.com/stretchr/testify/mock"

	storage "github.com/AmadlaOrg/hery/storage"
)

// MockEntityCmdUtil is an autogenerated mock type for the IUtil type
type MockEntityCmdUtil struct {
	mock.Mock
}

type MockEntityCmdUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEntityCmdUtil) EXPECT() *MockEntityCmdUtil_Expecter {
	return &MockEntityCmdUtil_Expecter{mock: &_m.Mock}
}

// Concoct provides a mock function with given fields: cmd, args, handler
func (_m *MockEntityCmdUtil) Concoct(cmd *cobra.Command, args []string, handler func(*storage.AbsPaths, []string)) error {
	ret := _m.Called(cmd, args, handler)

	if len(ret) == 0 {
		panic("no return value specified for Concoct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*cobra.Command, []string, func(*storage.AbsPaths, []string)) error); ok {
		r0 = rf(cmd, args, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityCmdUtil_Concoct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Concoct'
type MockEntityCmdUtil_Concoct_Call struct {
	*mock.Call
}

// Concoct is a helper method to define mock.On call
//   - cmd *cobra.Command
//   - args []string
//   - handler func(*storage.AbsPaths , []string)
func (_e *MockEntityCmdUtil_Expecter) Concoct(cmd interface{}, args interface{}, handler interface{}) *MockEntityCmdUtil_Concoct_Call {
	return &MockEntityCmdUtil_Concoct_Call{Call: _e.mock.On("Concoct", cmd, args, handler)}
}

func (_c *MockEntityCmdUtil_Concoct_Call) Run(run func(cmd *cobra.Command, args []string, handler func(*storage.AbsPaths, []string))) *MockEntityCmdUtil_Concoct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*cobra.Command), args[1].([]string), args[2].(func(*storage.AbsPaths, []string)))
	})
	return _c
}

func (_c *MockEntityCmdUtil_Concoct_Call) Return(_a0 error) *MockEntityCmdUtil_Concoct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityCmdUtil_Concoct_Call) RunAndReturn(run func(*cobra.Command, []string, func(*storage.AbsPaths, []string)) error) *MockEntityCmdUtil_Concoct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEntityCmdUtil creates a new instance of MockEntityCmdUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntityCmdUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntityCmdUtil {
	mock := &MockEntityCmdUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
