// Code generated by mockery v2.43.2. DO NOT EDIT.

package json

import mock "github.com/stretchr/testify/mock"

// MockUtilJson is an autogenerated mock type for the Json type
type MockUtilJson struct {
	mock.Mock
}

type MockUtilJson_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUtilJson) EXPECT() *MockUtilJson_Expecter {
	return &MockUtilJson_Expecter{mock: &_m.Mock}
}

// NewMockUtilJson creates a new instance of MockUtilJson. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUtilJson(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUtilJson {
	mock := &MockUtilJson{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
