# TODO: Need to add other schema details like data type, constrains, etc. From the information here we need to be able to regenerate the schema and the .hery file. Maybe add another table for other details from the schema

entities: {
  shape: sql_table
  id: INT {constraint: primary_key}
  _id: TEXT {constraint: unique}
  _entity: TEXT
  _meta: TEXT
  _body: TEXT
  Name: TEXT
  RepoUrl: TEXT
  Origin: TEXT
  Version: TEXT
  IsLatestVersion: BOOLEAN
  IsPseudoVersion: BOOLEAN
  AbsPath: TEXT
  Have: BOOLEAN
  Hash: TEXT
  Exist: BOOLEAN
  Schema: TEXT
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

meta: {
  shape: sql_table
  id: INT {constraint: primary_key}
  entities_id: INT {constraint: foreign_key}
  body__id: INT {constraint: foreign_key}
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

body: {
  shape: sql_table
  id: INT {constraint: primary_key}
  entities_id: INT {constraint: foreign_key}
  schema_property_id: INT {constraint: foreign_key}
  _id: TEXT
  property_name: TEXT
  property_value: TEXT
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

entity_inclusion: {
  shape: sql_table
  parent_body__id: INT {constraint: foreign_key}
  child_body__id: INT {constraint: foreign_key}
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

schema: {
  shape: sql_table
  id: INT {constraint: primary_key}
  entities_id: INT {constraint: foreign_key}
  \$id: TEXT
  title: TEXT
  description: TEXT
  type: TEXT
  required: TEXT
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

schema_properties: {
  shape: sql_table
  id: INT {constraint: primary_key}
  schema_id: INT {constraint: foreign_key}
  schema_property_id: INT {constraint: foreign_key}
  description: TEXT
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

schema_property: {
  shape: sql_table
  id: INT {constraint: primary_key}
  root_schema_id: INT {constraint: foreign_key}
  schema_item_id: INT {constraint: foreign_key}
  name: TEXT
  type: ENUM \[string, number, integer, boolean, array, object, null\]
  format: TEXT
  pattern: TEXT
  default: TEXT
  enum: TEXT
  const: TEXT
  minLength: INT
  maxLength: INT
  minimum: INT
  maximum: INT
  multipleOf: FLOAT
  description: TEXT
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

schema_item_properties: {
  shape: sql_table
  id: INT {constraint: primary_key}
  schema_item_id: INT {constraint: foreign_key}
  schema_property_id: INT {constraint: foreign_key}
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

schema_item: {
  shape: sql_table
  id: INT {constraint: primary_key}
  type: ENUM \[string, number, integer, boolean, array, object, null\]
  description: TEXT
  insert_date_time: DATETIME
  update_date_time: DATETIME
}

entities.id -> meta.entities_id
meta.body__id -> body._id
entities.id -> body.entities_id
entities.id -> schema.entities_id

schema.id -> schema_properties.schema_id
schema_properties.schema_property_id -> schema_property.id
schema_item_properties.schema_item_id -> schema_item.id
schema_item_properties.schema_property_id -> schema_property.id
schema_property.schema_item_id -> schema_item.id

entity_inclusion.parent_body__id -> body.id
entity_inclusion.child_body__id -> body.id

body.schema_property_id -> schema_property.id

schema_property.root_schema_id -> schema.id
