grid-rows: 3

classes: {
  white square: {
    width: 120
    style: {
      fill: white
      stroke: cornflowerblue
      stroke-width: 10
      font-color: black
    }
  }
  block: {
    style: {
      text-transform: uppercase
      font-color: white
      fill: darkcyan
      stroke: black
    }
  }
}

".hery file".class: white square
JSON-Schema.class: white square

HERY: {
  width: 800
  class: block
  style: {
    fill: lightcyan
    stroke: darkcyan
    font-color: black
    stroke-width: 8
  }
}

SQLite 3.class: block
File System.class: block
