x1: {
  label: "Hery"
  x2: {
    label: "Collections"
    x3: {
      label: "Collection #1"
      x4x1: {
        label: "Entity"
      }
      x4x2: {
        label: "Entity"
      }
    }
    x4: {
      label: "Collection #2"
      x5x2: {
        label: "Entity"
      }
      x5x3: {
        label: "Entity"
      }
    }
  }
}