// Code generated by mockery v2.53.6. DO NOT EDIT.

package get

import (
	entity "github.com/AmadlaOrg/hery/entity"
	mock "github.com/stretchr/testify/mock"

	storage "github.com/AmadlaOrg/hery/storage"
)

// MockEntityGet is an autogenerated mock type for the Getter interface
type MockEntityGet struct {
	mock.Mock
}

type MockEntityGet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEntityGet) EXPECT() *MockEntityGet_Expecter {
	return &MockEntityGet_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: storagePaths, entities
func (_m *MockEntityGet) Get(storagePaths *storage.AbsPaths, entities []string) error {
	ret := _m.Called(storagePaths, entities)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.AbsPaths, []string) error); ok {
		r0 = rf(storagePaths, entities)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityGet_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEntityGet_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - storagePaths *storage.AbsPaths
//   - entities []string
func (_e *MockEntityGet_Expecter) Get(storagePaths interface{}, entities interface{}) *MockEntityGet_Get_Call {
	return &MockEntityGet_Get_Call{Call: _e.mock.On("Get", storagePaths, entities)}
}

func (_c *MockEntityGet_Get_Call) Run(run func(storagePaths *storage.AbsPaths, entities []string)) *MockEntityGet_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage.AbsPaths), args[1].([]string))
	})
	return _c
}

func (_c *MockEntityGet_Get_Call) Return(_a0 error) *MockEntityGet_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityGet_Get_Call) RunAndReturn(run func(*storage.AbsPaths, []string) error) *MockEntityGet_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetInTmp provides a mock function with given fields: entities
func (_m *MockEntityGet) GetInTmp(entities []string) (storage.AbsPaths, error) {
	ret := _m.Called(entities)

	if len(ret) == 0 {
		panic("no return value specified for GetInTmp")
	}

	var r0 storage.AbsPaths
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (storage.AbsPaths, error)); ok {
		return rf(entities)
	}
	if rf, ok := ret.Get(0).(func([]string) storage.AbsPaths); ok {
		r0 = rf(entities)
	} else {
		r0 = ret.Get(0).(storage.AbsPaths)
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(entities)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityGet_GetInTmp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInTmp'
type MockEntityGet_GetInTmp_Call struct {
	*mock.Call
}

// GetInTmp is a helper method to define mock.On call
//   - entities []string
func (_e *MockEntityGet_Expecter) GetInTmp(entities interface{}) *MockEntityGet_GetInTmp_Call {
	return &MockEntityGet_GetInTmp_Call{Call: _e.mock.On("GetInTmp", entities)}
}

func (_c *MockEntityGet_GetInTmp_Call) Run(run func(entities []string)) *MockEntityGet_GetInTmp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockEntityGet_GetInTmp_Call) Return(_a0 storage.AbsPaths, _a1 error) *MockEntityGet_GetInTmp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityGet_GetInTmp_Call) RunAndReturn(run func([]string) (storage.AbsPaths, error)) *MockEntityGet_GetInTmp_Call {
	_c.Call.Return(run)
	return _c
}

// download provides a mock function with given fields: storagePaths, entitiesMeta
func (_m *MockEntityGet) download(storagePaths *storage.AbsPaths, entitiesMeta []entity.Entity) error {
	ret := _m.Called(storagePaths, entitiesMeta)

	if len(ret) == 0 {
		panic("no return value specified for download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.AbsPaths, []entity.Entity) error); ok {
		r0 = rf(storagePaths, entitiesMeta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityGet_download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'download'
type MockEntityGet_download_Call struct {
	*mock.Call
}

// download is a helper method to define mock.On call
//   - storagePaths *storage.AbsPaths
//   - entitiesMeta []entity.Entity
func (_e *MockEntityGet_Expecter) download(storagePaths interface{}, entitiesMeta interface{}) *MockEntityGet_download_Call {
	return &MockEntityGet_download_Call{Call: _e.mock.On("download", storagePaths, entitiesMeta)}
}

func (_c *MockEntityGet_download_Call) Run(run func(storagePaths *storage.AbsPaths, entitiesMeta []entity.Entity)) *MockEntityGet_download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage.AbsPaths), args[1].([]entity.Entity))
	})
	return _c
}

func (_c *MockEntityGet_download_Call) Return(_a0 error) *MockEntityGet_download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityGet_download_Call) RunAndReturn(run func(*storage.AbsPaths, []entity.Entity) error) *MockEntityGet_download_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEntityGet creates a new instance of MockEntityGet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntityGet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntityGet {
	mock := &MockEntityGet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
